### ISSUE TITLE
Please upload a video in Readme.md

### ISSUE THREAD

**Issue by DolBaKi** [SuhJae/WebCraftShare-Web#1]
I think this is so good.
But, if you want your project exposed others, you could take a video introducing your project, runnning your project and upload your video on youtube. I strongly recommend it.

안녕하세요. SEF2023을 통해 이 깃허브를 알게 되었어요!! 재웅님의 조선스페이스 웹사이트를 보고 HTML과 CSS를 다루시는 능력이 꽤나 뛰어나다는 것을 느꼈어요. 그런데, 자신이 사이트의 디자인을 변경할 때마다 불편해서 이렇게 웹사이트를 쉽게 수정할 수 있는 웹크래프트를 만드신 거에다가 깃허브에 올려주시다니 너무 감사해요!! 조선스페이스 다음으로 만들어질 웹사이트 궁궁유유도 기대하고 있어요!! 깃허브에 올린 것들을 영상으로 찍어서 설명하고 시연하는 영상을 제작하신다면 더욱 도움되실 것 같아요. 전에 맥북쓰시던 거 같은데 이번에 파컷 제대로 사용하실 수 있으실 거 같습니다 ㅋㅋㅋ 깃허브 자주 놀러올게요!!

**Comment by SuhJae** [comment]
안녕하세요!
제 깃허브에 방문해 주셔서 감사합니다! 긍정적인 피드백과 제안을 비롯해 제 프로젝트에 관심을 가져 주셔서 감사합니다. 영상 제작에 대한 제안도 고려해 볼게요! (사실 저희 학교 학생들이 HTML CSS JS의 기초를 쉽게 배우고 친구들과 자신이 만든 결과물을 쉽게 공유하기 위해 시작한 프로젝트인데 이렇게 봐 주셔서 감사합니다!) 맥북과 파컷에 관한 조언도 재미있네요! (사실 매일 과제로 영상 1,2 개씩 뽑아내고 있어요 😅) 더욱 발전하는 모습으로 보답하겠습니다!
좋은 하루 보내세요!
